config/routes.rb
Rails.application.routes.draw do
  resources :todolists do
    resources :todoitems do
    member do
        patch :complete
      end
    end
  end
  devise_for :users
  get 'welcome/index'

  resources :messages

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  validates :title, presence: true,
            length: { minimum: 5 }
  validates :text, presence: true,
            length: { minimum: 5, maximum: 250}
  belongs_to :user
end

app/models/todoitem.rb
class Todoitem < ApplicationRecord
  belongs_to :todolist

  def completed?
    !completedtime.blank?
  end
end

app/models/todolist.rb
class Todolist < ApplicationRecord
  has_many :todoitems
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!, except:
  def index
    @messages = Message.all
  end

  def show
    @message = Message.find(params[:id])
  end

  def new
    @message = current_user.messages.build
  end

  def edit
    @message = Message.find(params[:id])
  end

  def create
    @message = current_user.messages.build(message_params)

    if @message.save
      redirect_to @message
    else
      render 'new'
    end
  end

  def update
    @message = Message.find(params[:id])

    if @message.update(message_params)
      redirect_to @message
    else
      render 'edit'
    end
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    redirect_to messages_path
  end

  private
    def message_params
      params.require(:message).permit(:title, :text)
    end

end

app/controllers/todoitems_controller.rb
class TodoitemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_todolist
  before_action :set_todoitem, except: [:create]

  def create
    @todoitem = @todolist.todoitems.create(todoitem_params)

    redirect_to @todolist
  end

  def destroy
    if @todoitem.destroy
      flash[:success] = "Task was deleted"
    else
      flash[:error] = "Task could not be deleted"
    end
    redirect_to @todolist
  end

  def complete
    @todoitem.update_attribute(:completedtime, Time.now)

    redirect_to @todolist, notice: "Todo item completed";
  end

  private

  def set_todolist
    @todolist = Todolist.find(params[:todolist_id])
  end

  def set_todoitem
    @todoitem = @todolist.todoitems.find(params[:id])
  end

  def todoitem_params
    params[:todoitem].permit(:content)
  end

end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_todolist, only: [:show, :edit, :update, :destroy]

  # GET /todolists
  # GET /todolists.json
  def index
    @todolists = Todolist.all
  end

  # GET /todolists/1
  # GET /todolists/1.json
  def show
  end

  # GET /todolists/new
  def new
    @todolist = Todolist.new
  end

  # GET /todolists/1/edit
  def edit
  end

  # POST /todolists
  # POST /todolists.json
  def create
    @todolist = Todolist.new(todolist_params)

    respond_to do |format|
      if @todolist.save
        format.html { redirect_to @todolist, notice: 'Todolist was successfully created.' }
        format.json { render :show, status: :created, location: @todolist }
      else
        format.html { render :new }
        format.json { render json: @todolist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todolists/1
  # PATCH/PUT /todolists/1.json
  def update
    respond_to do |format|
      if @todolist.update(todolist_params)
        format.html { redirect_to @todolist, notice: 'Todolist was successfully updated.' }
        format.json { render :show, status: :ok, location: @todolist }
      else
        format.html { render :edit }
        format.json { render json: @todolist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todolists/1
  # DELETE /todolists/1.json
  def destroy
    @todolist.destroy
    respond_to do |format|
      format.html { redirect_to todolists_url, notice: 'Todolist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todolist
      @todolist = Todolist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todolist_params
      params.require(:todolist).permit(:title, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/todoitems_helper.rb
module TodoitemsHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller.controller_name %>">
  <p class="alert alert-success"><%= notice %></p>
  <p class="alert alert-danger"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for @message do |f| %>

    <% if @message.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@message.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @message.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>

    <p>
      <%= f.submit %>
    </p>

<% end %>

app/views/messages/edit.html.erb
<h1>Edit message</h1>
<ul>
  <li><%= link_to 'Home', controller: 'welcome' %></li>
  <li class="active"><%= link_to 'Message board', controller: 'messages' %></li>
  <li><%= link_to 'Create message', new_message_path %></li>
  <li><%= link_to 'Todo', todolists_path %></li>
</ul>

<p id="notice"><%= notice %></p>

<p class="navbar-text pull-right">
  <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
</p>

<%= render 'form' %>


<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Message board</h1>
<ul>
  <li><%= link_to 'Home', controller: 'welcome' %></li>
  <li class="active"><%= link_to 'Message board', controller: 'messages' %></li>
  <li><%= link_to 'Create message', new_message_path %></li>
  <li><%= link_to 'Todo', todolists_path %></li>
</ul>



<p class="navbar-text pull-right">
  <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
</p>

<table>
  <tr class="<%= cycle('list_line_odd', 'list_line_even')%>">
    <th>Title</th>
    <th>Text</th>
    <th>User</th>
    <th colspan="3"></th>
  </tr>

  <% @messages.each do |message| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even')%>">
        <td class="list_title"><%= message.title %></td>
        <td class="list_text"><%= message.text %></td>
        <td class="list_user"><%= message.user.email %></td>
        <td class="list_actions"><%= link_to 'Show', message_path(message), class: 'link_to_text_color' %><br/>

          <% if message.user == current_user %>
          <%= link_to 'Edit', edit_message_path(message), class: 'link_to_text_color'%><br/>
          <%= link_to 'Delete', message_path(message),
          method: :delete,
          data: { confirm: 'Are you sure?' }, class: 'link_to_text_color' %>
          <% end %>

        </td>
      </tr>
  <% end %>
</table>
<br/>
<%= link_to 'New message', new_message_path, class: 'link_to_text_color'%>

app/views/messages/new.html.erb
<h1>Create a message</h1>
<ul>
  <li><%= link_to 'Home', controller: 'welcome' %></li>
  <li><%= link_to 'Message board', controller: 'messages' %></li>
  <li class="active"><%= link_to 'Create message', new_message_path %></li>
  <li><%= link_to 'Todo', todolists_path %></li>
</ul>

<p id="notice"><%= notice %></p>

<p class="navbar-text pull-right">
  <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
</p>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @message.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @message.text %>
</p>

<%= link_to 'Back', messages_path %>

app/views/todoitems/_form.html.erb
<%= form_for([@todolist, @todolist.todoitems.build]) do |f| %>
    <%= f.text_field :content, placeholder: "New Todo" %>
    <%= f.submit %>
<% end %>

app/views/todoitems/_todoitem.html.erb
<% if todoitem.completed? %>
    <div>
      <p><s><%= todoitem.content %></s></p>
    </div>
    <div>
      <%= link_to "Complete!", complete_todolist_todoitem_path(@todolist, todoitem.id), method: :patch %>
    </div>
    <div>
      <%= link_to "Delete", todolist_todoitem_path(@todolist, todoitem.id), method: :delete, data: { confirm: "Are you sure?" } %>
    </div>
  <% else %>
    <div>
      <p><s><%= todoitem.content %></s></p>
    </div>
    <div>
      <%= link_to "Complete!", complete_todolist_todoitem_path(@todolist, todoitem.id), method: :patch %>
    </div>
    <div>
      <%= link_to "Delete", todolist_todoitem_path(@todolist, todoitem.id), method: :delete, data: { confirm: "Are you sure?" } %>
    </div>
<% end %>

app/views/todolists/_form.html.erb
<%= form_with(model: todolist, local: true) do |form| %>
  <% if todolist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todolist.errors.count, "error") %> prohibited this todolist from being saved:</h2>

      <ul>
      <% todolist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :todolist_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :todolist_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todolists/edit.html.erb
<h1>Editing Todolist</h1>

<%= render 'form', todolist: @todolist %>

<%= link_to 'Show', @todolist %> |
<%= link_to 'Back', todolists_path %>

app/views/todolists/index.html.erb
<h1>Todolists</h1>
<ul>
  <li><%= link_to 'Home', controller: 'welcome' %></li>
  <li><%= link_to 'Message board', controller: 'messages' %></li>
  <li><%= link_to 'Create message', new_message_path %></li>
  <li class="active"><%= link_to 'Todo', todolists_path %></li>
</ul>



<p class="navbar-text pull-right">
  <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
</p>
<table>
  <thead>
    <tr>
      <th>Teams</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>



  <tbody>
    <% @todolists.each do |todolist| %>
      <tr>
        <td><%= todolist.title %></td>
        <td><%= todolist.description %></td>
        <td><%= link_to 'Show', todolist %></td>

        <td><%= link_to 'Edit', edit_todolist_path(todolist) %></td>
        <td><%= link_to 'Destroy', todolist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todolist', new_todolist_path %>

app/views/todolists/new.html.erb
<h1>New Todolist</h1>
<ul>
  <li><%= link_to 'Home', controller: 'welcome' %></li>
  <li><%= link_to 'Message board', controller: 'messages' %></li>
  <li><%= link_to 'Create message', new_message_path %></li>
  <li class="active"><%= link_to 'Todo', todolists_path %></li>
</ul>

<p id="notice"><%= notice %></p>

<p class="navbar-text pull-right">
  <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
</p>

<%= render 'form', todolist: @todolist %>

<%= link_to 'Back', todolists_path %>

app/views/todolists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todolist.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @todolist.description %>
</p>

<div id="todoitems_wrapper">
  <%= render @todolist.todoitems %>
  <div id="form">
    <%= render "todoitems/form" %>
  </div>
</div>

<%= link_to 'Edit', edit_todolist_path(@todolist) %> |
<%= link_to 'Back', todolists_path %>

app/views/welcome/index.html.erb
<h1>Welcome to the starting page</h1>
<ul>
  <li class="active"><%= link_to 'Home', controller: 'welcome' %></li>
  <li><%= link_to 'Message board', controller: 'messages' %></li>
  <li><%= link_to 'Create message', new_message_path %></li>
  <li><%= link_to 'Todo', todolists_path %></li>
</ul>



<p class="navbar-text pull-right">
  <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
</p>

<p>Welcome! This is a message/todolist application, targeting family or groups.
  Here you can create and view messages and todolist as you please!</p>